manifest: clarify the zero length layers array
opencontainers/image-spec pull request #1013
Opened 2023-02-10 00:09 UTC by vbatts

through the recent discussions of #999 and differences from image manifest and artifact manifest, it is important to clarify that layers can be a zero-length array.

Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

2023-02-10 00:14 UTC, sudo-bmitch requested changes
I believe this is a breaking change. There is an assumption of at least one layer that has likely been included in registries and client tooling. The spec includes the following places were we indicate it must have at least one layer:

https://github.com/opencontainers/image-spec/blob/main/schema/image-manifest-schema.json#L23
https://github.com/opencontainers/image-spec/blob/main/specs-go/v1/manifest.go#L31
https://github.com/opencontainers/image-spec/blob/main/img/media-types.png

2023-02-10 02:17 UTC, vbatts commented
no, I am sure that it exists in a multiple understanding, and to clarify that zero-layers are allowed would not be a breaking change

2023-02-10 20:55 UTC, tianon commented
I did a little testing with https://explore.ggcr.dev/?image=tianon/scratch and https://explore.ggcr.dev/?image=tianon/scratch:oci and then https://explore.ggcr.dev/?image=tianon/scratch:nolayers (Docker media types with a zero-length layers array created directly by `docker build` tooling `FROM scratch \n CMD []`, OCI media types with a zero-length layers array, and finally OCI media types with no layers array at all):

```console
$ crane manifest tianon/scratch:nolayers
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "config": {
    "mediaType": "application/vnd.oci.image.config.v1+json",
    "size": 290,
    "digest": "sha256:132144ab4e026a9b1ca95b5dfeb9892d12f0c2c1368ae0b4bdca408e62768396"
  }
}

$ docker pull tianon/scratch:nolayers
nolayers: Pulling from tianon/scratch
Digest: sha256:aad957e043852ec4cd630cabb56da94c024a0bb3a72bd4d530a13b8f6b752ca7
Status: Downloaded newer image for tianon/scratch:nolayers
docker.io/tianon/scratch:nolayers

$ sudo ctr i pull docker.io/tianon/scratch:nolayers
docker.io/tianon/scratch:nolayers:                                                resolved       |++++++++++++++++++++++++++++++++++++++| 
manifest-sha256:aad957e043852ec4cd630cabb56da94c024a0bb3a72bd4d530a13b8f6b752ca7: done           |++++++++++++++++++++++++++++++++++++++| 
config-sha256:132144ab4e026a9b1ca95b5dfeb9892d12f0c2c1368ae0b4bdca408e62768396:   done           |++++++++++++++++++++++++++++++++++++++| 
elapsed: 1.6 s                                                                    total:  271.0  (169.0 B/s)                                       
unpacking linux/amd64 sha256:aad957e043852ec4cd630cabb56da94c024a0bb3a72bd4d530a13b8f6b752ca7...
done: 8.646616ms	
```

2023-02-13 22:40 UTC, sajayantony commented
Thanks @tianon - Tested with ACR as well - 
```bash 
❯ oras cp docker.io/tianon/scratch:nolayers sajay.azurecr.io/scratch:nolayers
Copied [registry] docker.io/tianon/scratch:nolayers => [registry] sajay.azurecr.io/scratch:nolayers
Digest: sha256:aad957e043852ec4cd630cabb56da94c024a0bb3a72bd4d530a13b8f6b752ca7

❯ oras manifest get sajay.azurecr.io/scratch:nolayers --pretty
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "config": {
    "mediaType": "application/vnd.oci.image.config.v1+json",
    "size": 290,
    "digest": "sha256:132144ab4e026a9b1ca95b5dfeb9892d12f0c2c1368ae0b4bdca408e62768396"
  }
}
```

2023-02-25 10:06 UTC, sudo-bmitch commented
Can we close this?

2023-03-02 18:40 UTC, vbatts commented
Most registries support this, but 2 do not (#1025). In the favor of portability scratch config and layers (#1023) would be more preferable for folks look to "misuse" the image spec to also distribute arbitrary blobs

2023-03-02 18:40 UTC, closed without merging