manifest: clarify that `layers` is technically OPTIONAL
opencontainers/image-spec pull request #1016
Opened 2023-02-10 21:06 UTC by vbatts

Surprisingly, this field was not clearly marked as REQUIRED or OPTIONAL, and is generally allowed as an OPTIONAL field.

Per the conversation in slack with @tianon and @thaJeztah: https://explore.ggcr.dev/?image=tianon/scratch:nolayers

```
Docker-Content-Digest: sha256:aad957e043852ec4cd630cabb56da94c024a0bb3a72bd4d530a13b8f6b752ca7
Content-Length: 271
Content-Type: application/vnd.oci.image.manifest.v1+json

$ crane manifest tianon/scratch:nolayers | jq .
{
	"schemaVersion": 2,
	"mediaType": "application/vnd.oci.image.manifest.v1+json",
	"config": {
		"mediaType": "application/vnd.oci.image.config.v1+json",
		"size": 290,
		"digest": "sha256:132144ab4e026a9b1ca95b5dfeb9892d12f0c2c1368ae0b4bdca408e62768396"
	}
}
```

Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

2023-02-10 21:09 UTC, thaJeztah approved these changes
SGTM

only question; do we need to verify if existing implementation would bail out on "field missing" vs "field present, but empty slice"?

2023-02-10 21:12 UTC, sajayantony approved these changes

2023-02-10 21:18 UTC, sudo-bmitch commented
The following parts of the spec should be kept aligned:

- https://github.com/opencontainers/image-spec/blob/main/schema/image-manifest-schema.json#L36
- https://github.com/opencontainers/image-spec/blob/main/specs-go/v1/manifest.go#L31

2023-02-10 21:46 UTC, jdolitsky submitted a review, later dismissed

2023-02-10 22:21 UTC, vbatts commented
fixed PTAL

2023-02-12 13:08 UTC, vbatts commented
cc @opencontainers/image-spec-maintainers

2023-02-13 20:09 UTC, sajayantony approved these changes

2023-02-14 17:21 UTC, thaJeztah approved these changes
LGTM

2023-02-25 10:05 UTC, sudo-bmitch requested changes
I believe we should close this to go with the "scratch layer" option.

2023-03-02 18:36 UTC, vbatts commented
while many registries support "no layers", not all do, and truly in the context of _images_, this does not make sense.
This PR was proposed as a compromise for the #999 removal, which has been a fairly uncompromising change.

2023-03-02 18:36 UTC, closed without merging