Add constants for "index.json" and "blobs" alongside "oci-layout" as parts of the layout specification
opencontainers/image-spec pull request #1071
Opened 2023-06-02 17:29 UTC by sparr

The [layout spec](https://github.com/opencontainers/image-spec/blob/v1.0/image-layout.md#content) requires three named files/directories. The `oci-layout` file name is already exposed as a constant from this package. This PR adds exported constants for `index.json` and `blobs`.

Closes #1069

2023-06-02 18:51 UTC, sudo-bmitch requested changes
Just a few minor comment nits. While we're here, I think we should also fix line 18. My attempt would look like:

```
// ImageLayoutFile is the file name containing ImageLayout in an OCI Image Layout
```

2023-06-02 18:51 UTC, sudo-bmitch commented on specs-go/v1/layout.go
> +	// ImageIndexFile is the file name for an oci image index
```suggestion
	// ImageIndexFile is the file name of the entry point for references and descriptors in an OCI Image Layout
```

2023-06-02 18:51 UTC, sudo-bmitch commented on specs-go/v1/layout.go
> +	// ImageBlobsDir is the directory name for an oci image blobs directory
```suggestion
	// ImageBlobsDir is the directory name for the content addressable storage in an OCI Image Layout
```

2023-06-02 19:03 UTC, sparr commented on specs-go/v1/layout.go
> +	// ImageIndexFile is the file name for an oci image index
Done, verbatim

2023-06-02 19:04 UTC, sparr commented on specs-go/v1/layout.go
> +	// ImageBlobsDir is the directory name for an oci image blobs directory
Done, with alternate verbiage "contain[ing] content-addressable blobs" from https://github.com/opencontainers/image-spec/blob/v1.1.0-rc2/image-layout.md#blobs

2023-06-02 21:33 UTC, sudo-bmitch approved these changes
LGTM

2023-06-03 18:54 UTC, TerryHowe approved these changes
/lgtm

although obviously not a maintainer

2023-06-23 02:36 UTC, tianon approved these changes

2023-06-23 02:37 UTC, tianon commented
(I don't think I personally plan to use these in the tools I've written that currently hard-code these values, but I do think adding them increases the consistency of the constants we provide :heart:)

2023-06-23 02:37 UTC, merged