update implementations rkt project has ended
opencontainers/image-spec pull request #1148
Opened 2023-11-08 10:18 UTC by dejanu

Update md since CoreOS rkt got dismantled, and there are no plans to push the development forward.
Also in the CNCF landscape, the project is marked as [Project ended]

2023-11-08 10:24 UTC, jonboulle submitted a review, later dismissed

2023-11-08 15:47 UTC, sudo-bmitch requested changes
I'm leaning towards adding a section at the bottom of the file:

```
## Former Projects

OCI would like to recognize the following projects that are no longer actively maintained but have contributed to the adoption of OCI:
```

And then move rkt under that section. That way the "Projects or Companies currently adopting the OCI Image Specification" heading doesn't need to be changed or have a footnote.

2023-11-12 22:46 UTC, sudo-bmitch approved these changes
LGTM, thanks!

2023-11-12 22:47 UTC, sudo-bmitch requested changes
I spoke too soon. Would you squash the commits and resolve the DCO error.

2023-11-14 14:11 UTC, sudo-bmitch approved these changes
LGTM, thanks!

2023-11-14 20:11 UTC, tianon approved these changes

2023-11-14 20:11 UTC, merged