media-types: Fix broken links
opencontainers/image-spec pull request #1163
Opened 2024-02-04 08:31 UTC by coolljt0725

Related to https://github.com/distribution/distribution/pull/4101, This PR move `spec/manifest-v2-2.md` to `content/spec/manifest-v2-2.md`

2024-02-04 13:02 UTC, sudo-bmitch requested changes
My preference is to depend on a tag rather than the master branch. Once the 3.0 release goes GA there, we can adjust the tags and paths together. It also looks like the image manifest anchor was been wrong so this is a good opportunity to fix that too.

2024-02-04 13:02 UTC, sudo-bmitch commented on media-types.md
> +- [application/vnd.docker.distribution.manifest.v2+json](https://github.com/distribution/distribution/blob/master/docs/content/spec/manifest-v2-2.md#image-manifest-field-descriptions)
```suggestion
- [application/vnd.docker.distribution.manifest.v2+json](https://github.com/distribution/distribution/blob/v2.8.3/docs/spec/manifest-v2-2.md#image-manifest)
```

2024-02-05 00:50 UTC, coolljt0725 commented on media-types.md
> +- [application/vnd.docker.distribution.manifest.list.v2+json](https://github.com/distribution/distribution/blob/master/docs/content/spec/manifest-v2-2.md#manifest-list)
Good suggestion, agree. Thanks

2024-02-05 00:59 UTC, coolljt0725 commented
updated according to @sudo-bmitch 's suggestions.

2024-02-05 13:39 UTC, sudo-bmitch approved these changes
LGTM. I'd recommend holding off on the final merge until after the 1.1.0 vote completes.

2024-02-17 02:51 UTC, tianon approved these changes

2024-02-17 02:51 UTC, merged