Support the media type `application/vnd.oci.image.layer.v1.raw`
opencontainers/image-spec pull request #1197
Opened 2024-09-03 11:00 UTC by wzshiming

This defines a new MediaType which is the original file without any processing, marks its path in the annotation.
This will be very helpful for large models.

2024-09-03 13:00 UTC, gaius-qi commented
+1

`application/vnd.oci.image.layer.v1.raw` can remove the time-consuming compression and decompression of the AI Model weight. The compression rate of Gzip for the model is low, and the compression and decompression time can be increased.

2024-09-03 15:11 UTC, sudo-bmitch commented
This gets a soft NACK from me. Knowing the path in the image is something the artifact should be unaware of. Different containers may want to mount the content of the same artifact in different locations. If there is a tight connection between the artifact and the image, then the artifact should likely be shipped as a new layer in the image and image-spec already defines how layers are added. Also, a media type that indicates the content is an unknown byte steam is already handled by using `[application/octet-stream](https://www.iana.org/assignments/media-types/application/octet-stream)`.

An "unknown" media type breaks artifacts outside of the Kubernetes context, or creates artifacts that can only be used when structured in the Kubernetes mandated format. E.g. WASM would need to redefine their artifact specification, or ship two separate artifacts, allow their content to be mounted as a volume.

I think it would be better for Kubernetes to support arbitrary artifacts with an enhanced volume syntax that specifies which blob in the artifact to mount with a specific filename. I mentioned that in [my review of the KEP](https://github.com/kubernetes/enhancements/pull/4642#pullrequestreview-2096006727) but that was pushed off to a future enhancement so that the simplified proposal could be implemented faster.

2024-09-03 15:13 UTC, sudo-bmitch reviewed
This gets a soft NACK from me. Knowing the path in the image is something the artifact should be unaware of. Different containers may want to mount the content of the same artifact in different locations. If there is a tight connection between the artifact and the image, then the artifact should likely be shipped as a new layer in the image and image-spec already defines how layers are added. Also, a media type that indicates the content is an unknown byte steam is already handled by using [application/octet-stream](https://www.iana.org/assignments/media-types/application/octet-stream).

An "unknown" media type breaks artifacts outside of the Kubernetes context, or creates artifacts that can only be used when structured in the Kubernetes mandated format. E.g. WASM would need to redefine their artifact specification, or ship two separate artifacts, allow their content to be mounted as a volume.

I think it would be better for Kubernetes to support arbitrary artifacts with an enhanced volume syntax that specifies which blob in the artifact to mount with a specific filename. I mentioned that in https://github.com/kubernetes/enhancements/pull/4642#pullrequestreview-2096006727 but that was pushed off to a future enhancement so that the simplified proposal could be implemented faster.

2024-09-03 19:07 UTC, tianon commented
Agreed with Brandon; if compression is the bottleneck, I'd suggest using uncompressed (`application/vnd.oci.image.layer.v1.tar`), especially as using a standard tar header on the data instead of a custom annotation adds other benefits like all the existing standard container ecosystem tooling being able to do something meaningful with the blobs (`RUN --mount=type=image,...`, the new k8s functionality, https://oci.dag.dev, etc).

2024-09-04 03:35 UTC, wzshiming commented
Thanks for your reply, I've updated my content accordingly and commented on the previous discussion for anyone who might be interested in moving over here.

I think this is a great optimization for large files in images. I look forward to a discussion that will lead to a more acceptable solution. 🙏🙏🙏

2024-09-04 09:54 UTC, sftim commented
How will we persuade all container runtimes to adopt this special layer format; how will we provide compatibility for runtimes that don't yet include that support?

2024-09-04 09:56 UTC, sftim commented
Alternative: define a new type OCI artefact (not a layer) that represents a chunk of application data. This can then be mapped to something that looks like a file and mounted where a container can access it. For example, using a CSI driver and Kubernetes.

2024-09-04 10:26 UTC, wzshiming commented
> Alternative: define a new type OCI artefact (not a layer) that represents a chunk of application data. This can then be mapped to something that looks like a file and mounted where a container can access it. For example, using a CSI driver and Kubernetes.

You have a point, there seems to be a precedent for this approach. such as [application/vnd.in-toto+json](https://github.com/in-toto/attestation/blob/a7a9d0712d5115af3e8e1f6b3564158a1bbb73e4/spec/v1/statement.md),


https://oci.dag.dev/?image=docker/dockerfile:1.5.1
``` bash
crane manifest docker/dockerfile: 1.5.1 | jq .
{
    "schemaVersion": 2,
    "mediaType": "application/vnd.oci.image.index.v1+json",
    "manifests": [
...
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:cd6383b1260aee71593cb70bdd44d50daf1ba142ed54191972fce08694ddfe35",
            "size": 839,
            "platform": {
                "architecture": "unknown",
                "os": "unknown"
            },
            "annotations": {
                "vnd.docker.reference.digest": "sha256:e7748818724fa5f622da18698f9f5b16e0f32e5a6b9af888fd84053eb48e9cfd",
                "vnd.docker.reference.type": "attestation-manifest"
            }
        },
...
    ]
}
``` 


https://oci.dag.dev/?image=docker/dockerfile@sha256:cd6383b1260aee71593cb70bdd44d50daf1ba142ed54191972fce08694ddfe35
``` bash
crane manifest docker/dockerfile@sha256:cd6383b1260aee71593cb70bdd44d50daf1ba142ed54191972fce08694ddfe35 | jq .
{
    "schemaVersion": 2,
    "mediaType": "application/vnd.oci.image.manifest.v1+json",
    "config": {
        "mediaType": "application/vnd.oci.image.config.v1+json",
        "digest": "sha256:083187ca1ac1b4eebff9e2c982bb462d947a34e6d93be8a7d33491cf933881c9",
        "size": 241
    },
    "layers": [
        {
            "mediaType": "application/vnd.in-toto+json",
            "digest": "sha256:4297014349dde3f52863838747b5a4bacf2058d0951dae5b48025741611496a7",
            "size": 39882,
            "annotations": {
                "in-toto.io/predicate-type": "https://spdx.dev/Document"
            }
        },
        {
            "mediaType": "application/vnd.in-toto+json",
            "digest": "sha256:ff81f2987309a567da898c358437b2943cc297007b99491a4ea13f014b90a449",
            "size": 14542,
            "annotations": {
                "in-toto.io/predicate-type": "https://slsa.dev/provenance/v0.2"
            }
        }
    ]
}
```

2024-09-10 18:28 UTC, rchincha commented
There are other approaches to address the core requirement and better aligned with existing workflows?
https://github.com/opencontainers/image-spec/issues/1190

2024-09-12 19:34 UTC, sudo-bmitch requested changes
After thinking about this more, I'm switching to a hard NACK. To support artifacts in the KEP, that should be taken up on the K8s side. I don't think we should contort the definition of an OCI image to attempt to force them to accept what should be distributed as an OCI artifact.

2024-12-05 17:58 UTC, sudo-bmitch commented
I'm closing this out since it's been a few months and there don't appear to be any maintainers in favor of the change.

2024-12-05 17:58 UTC, closed without merging

2025-03-19 19:01 UTC, s3rj1k commented
@sudo-bmitch I known that this was closed, noticed that you mentioned `zstd compressed` tar layers, what about just `zstd compressed` raw file, no tar, one file per layer, could that be considered as extension?

2025-03-19 19:13 UTC, sudo-bmitch commented
> @sudo-bmitch I known that this was closed, noticed that you mentioned `zstd compressed` tar layers, what about just `zstd compressed` raw file, no tar, one file per layer, could that be considered as extension?

That's already a registered media type: https://www.iana.org/assignments/media-types/media-types.xhtml

Note that OCI does not typically direct runtimes on what they must support. Runtimes add capabilities and then once they are verified in production we standardize them for interoperability between different runtimes. In other words, we are typically a trailing spec. So you would first implement this in a runtime.

2025-03-19 19:17 UTC, s3rj1k commented
> Note that OCI does not typically direct runtimes on what they must support. Runtimes add capabilities and then once they are verified in production we standardize them for interoperability between different runtimes. In other words, we are typically a trailing spec. So you would first implement this in a runtime.

Hmm, that makes sense, thank you

2025-03-21 03:44 UTC, tianon commented
I'd also stress again that an uncompressed tar is just a binary header prefix on your data with filename, size, permissions, etc, and using that allows existing ecosystem tools to process and browse your data without any changes.  Your data is otherwise verbatim, it just starts with a bit of metadata in a binary format that you'd otherwise likely end up adding in JSON annotations (effectively reproducing a tar header, but less efficiently).  Please consider using an uncompressed tar header instead of raw data (compressed or otherwise).

2025-03-21 10:45 UTC, s3rj1k commented
> I'd also stress again that an uncompressed tar is just a binary header prefix on your data with filename, size, permissions, etc, and using that allows existing ecosystem tools to process and browse your data without any changes. Your data is otherwise verbatim, it just starts with a bit of metadata in a binary format that you'd otherwise likely end up adding in JSON annotations (effectively reproducing a tar header, but less efficiently). Please consider using an uncompressed tar header instead of raw data (compressed or otherwise).
> 
> **Edit:** see https://pkg.go.dev/archive/tar#Header for the exact fields

True, still consider the case of streaming data on per-layer basis, one-file-per-layer compressed with ztsd or gzip is simpler to stream compared to a file wrapped into tar.

2025-03-21 11:47 UTC, sudo-bmitch commented
> True, still consider the case of streaming data on per-layer basis, one-file-per-layer compressed with ztsd or gzip is simpler to stream compared to a file wrapped into tar.

Can you expand on that? Why is it simpler to stream data to a file on a filesystem using metadata in an external json format than with a tar header?

2025-03-21 13:02 UTC, s3rj1k commented
> > True, still consider the case of streaming data on per-layer basis, one-file-per-layer compressed with ztsd or gzip is simpler to stream compared to a file wrapped into tar.
> 
> Can you expand on that? Why is it simpler to stream data to a file on a filesystem using metadata in an external json format than with a tar header?

You won’t need to handle tar header in file itself codewise, just take binary blob directly and read it and unpack gzip/ztsd as stream if that file is even compressed, compression is optional basically.

View this streaming from a POV of some WebUI that wants to show content of the packed file in browser form for example. In this case it is simpler to get that extra data out of annotation and way safer memory wise and stream content from blob if that is requested.

Similar thing if done using tar you would need to partially parse each tar header file to get data out first, when parse again for content if that was requested.