docs: Added artifact.md to docs
opencontainers/image-spec pull request #957
Opened 2022-09-23 18:11 UTC by sajayantony

Added artifact.md and updated the media-types diagram dot and png.

Signed-off-by: Sajay Antony <sajaya@microsoft.com>

2022-09-24 13:40 UTC, sudo-bmitch requested changes
Thanks for running with this one. We also need to add a reference to `artifact.md` in the "Table of Contents" at the top of `spec.md`.

2022-09-24 13:40 UTC, sudo-bmitch commented on img/media-types.dot
> +  artifact -> manifest [label="1..1"] [constraint = false];
If this is capturing the "subject" field, then we also need two more self references like there is for `imageIndex`, and the reference is also optional, so `0..1`:

```suggestion
  artifact -> manifest [label="0..1"] [constraint = false];
  artifact -> artifact [label="0..1"];
  manifest -> manifest [label="0..1"];
```

I'm not sure how to capture that it's `0..1` for multiple targets and you can't have a manifest with both a subject of another manifest and an artifact, but that may be more detail than needed.

2022-09-24 13:40 UTC, sudo-bmitch commented on img/media-types.dot
> +  artifact -> layer[label="1..*"]
Since blobs are optional for artifacts, I think we want `0..*` here.

```suggestion
  artifact -> layer[label="0..*"]
```

2022-09-25 00:09 UTC, sudo-bmitch commented
The more I think about the subject field in the graphic, and anything with a descriptor to a manifest, the more I want a general manifest and blob in the graphic, and have pointers go to those general types. I'll do some digging into graphviz and see if there's a better way to draw it.

In the mean time, if another wants to approve this, I'll update my review and follow up with a separate PR.

2022-09-27 14:41 UTC, sudo-bmitch approved these changes
LGTM. There's still some work to do on the graphic, but this gets us in a better place.

2022-10-20 17:07 UTC, jonjohnsonjr approved these changes

2022-10-20 18:29 UTC, merged